# --- config for training a model --- #
train:
  overfit:
    hidden_size: 512
    ffn_size: 512
    heads: 32
    depth: 3
    max_epochs: 10
    max_length: 145
    batch_size: 64
    lr: 0.0001
    tokenizer: wp
    dropout: 0.0
    seed: 410
    shuffle: true
    data: kor2eng
  # just to test things out
  overfit_small:
    hidden_size: 512
    ffn_size: 512
    heads: 32
    depth: 3
    max_epochs: 200
    max_length: 145
    batch_size: 64
    lr: 0.0001
    tokenizer: wp
    dropout: 0.0
    seed: 410
    # shuffle the training set
    shuffle: true
    data: kor2eng_small

# --- config for building a tokenizer --- #
build:
  vocab_size: 20000
  pad: "[PAD]"
  pad_id: 0
  unk: "[UNK]"
  unk_id: 1
  bos: "[BOS]"
  bos_id: 2
  eos: "[EOS]"
  eos_id: 3

